### ISSUE TITLE
The pretrain model for ResNet101

### ISSUE THREAD

**Issue by lei1993** [filipradenovic/cnnimageretrieval-pytorch#18]
you say 'for some models, we have imported features (convolutions) from caffe because the image retrieval performance is higher for them' , what did you do for the caffe model to improve the performance?

**Comment by filipradenovic** [comment]
For example, for ResNet (50, 101, and 152) we have used the original weights from the [Deep Residual Networks paper](https://arxiv.org/pdf/1512.03385.pdf) that are available in [Caffe implementation](https://github.com/KaimingHe/deep-residual-networks). We have just imported weights in PyTorch framework and saved them on our servers so that they can be used for our training/testing. 

This was a design choice, as using the pretrained ResNet weights available in the [PyTorch model zoo](https://github.com/pytorch/vision/blob/master/torchvision/models/resnet.py) was performing worse than original weights.
