### ISSUE TITLE
How did you draw Fig2 in the "Fine-tuning CNN ..." paper?

### ISSUE THREAD

**Issue by SongZRui** [filipradenovic/cnnimageretrieval-pytorch#38]
![image](https://user-images.githubusercontent.com/38454808/58367050-dfa55400-7f0c-11e9-8e23-eaa9aa0ac5d6.png)
This figure is very impressive and straightforward to visualize the most distinguish patch of an image. I think it will do a great help in understanding which parts contributed more in my own work. Would you be so kind to opensource that code?
Many thanks in advance~

**Comment by filipradenovic** [comment]
This was done in MATLAB using MatConvNet. Because the final layer, in this case, is global max pooling (MAC), you can take the location of the max for each channel and estimate its location in the original image, as well as the size of the receptive field. This can be done with a function from MatConvNet [getVarReceptiveFields](http://www.vlfeat.org/matconvnet/mfiles/+dagnn/@DagNN/DagNN/#getvarreceptivefields-get-the-receptive-field-of-a-variable). For an example usage, check this [thread](https://github.com/vlfeat/matconvnet/issues/831).

**Comment by SongZRui** [comment]
Thank you so much. It's very helpful!
